/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 car.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.494, -0.536, -0.102]} rotation={[0, 0, Math.PI / 2]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353509_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353509_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353509_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353509_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.536, 0.841]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353548_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353548_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353548_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353548_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.536, 0.841]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353586_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353586_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353586_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353586_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.784, -0.536, 0.265]} rotation={[0, 0.384, -Math.PI / 2]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353628_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353628_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353628_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353628_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.784, -0.536, 0.589]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353666_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353666_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353666_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353666_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.536, 0.666]} rotation={[Math.PI, 0.384, Math.PI / 2]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353703_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353703_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353703_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353703_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.176, 0.189]} rotation={[0, 0.384, 2.063]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353742_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353742_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353742_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353742_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.176, 0.666]} rotation={[0, -0.384, 2.063]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353779_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353779_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353779_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353779_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.784, -0.286, 0.589]} rotation={[Math.PI / 2, -1.235, -Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353817_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353817_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353817_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353817_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.784, -0.286, 0.265]} rotation={[0, -1.235, -Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353858_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353858_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353858_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353858_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.784, -0.536, 0.589]} rotation={[-Math.PI, -1.235, -Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353896_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353896_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353896_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353896_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.536, 0.189]} rotation={[0, 0.384, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353934_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353934_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353934_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353934_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.536, 0.666]} rotation={[0, -0.384, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353972_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353972_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353972_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621353972_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.176, 0.189]} rotation={[2.217, -0.384, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354010_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354010_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354010_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354010_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.176, 0.666]} rotation={[-1.571, -0.384, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354047_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354047_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354047_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354047_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.448, -0.536, 0.66]} rotation={[-0.855, -0.288, 1.255]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354088_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354088_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354088_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354088_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.536, 0.666]} rotation={[1.484, 0.382, -1.544]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354127_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354127_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354127_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354127_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.594, -0.536, 0.189]} rotation={[-0.849, -0.289, -1.315]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354167_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354167_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354167_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354167_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.449, -0.116, 0.179]} rotation={[0.888, 0.05, 1.6]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354205_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354205_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354205_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354205_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.449, -0.536, 0.179]} rotation={[0.888, 0.006, 1.564]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354244_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354244_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354244_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354244_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.448, -0.536, 0.66]} rotation={[-1.488, 0.001, 1.577]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354290_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354290_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354290_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354290_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.448, -0.116, 0.66]} rotation={[-1.487, -0.057, 1.582]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354330_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354330_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354330_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354330_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.449, -0.116, 0.179]} rotation={[0, 0.897, -Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354369_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354369_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354369_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354369_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.448, -0.116, 0.66]} rotation={[1.571, 0.897, -3.141]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354408_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354408_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354408_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354408_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.448, -0.536, 0.66]} rotation={[Math.PI, 0.898, -Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354446_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354446_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354446_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354446_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.449, -0.536, 0.179]} rotation={[-1.571, 0.897, 3.141]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354485_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354485_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354485_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354485_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.449, -0.116, 0.179]} rotation={[0.699, 0.106, -1.628]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354524_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354524_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354524_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354524_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.084]} rotation={[-0.678, 0.103, 1.653]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354563_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354563_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354563_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354563_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.449, -0.116, 0.179]} rotation={[0.584, -0.208, -2.072]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354604_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354604_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354604_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354604_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.448, -0.116, 0.66]} rotation={[2.484, -0.217, -1.092]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354642_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354642_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354642_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354642_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.084]} rotation={[-2.161, -0.419, 2.116]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354680_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354680_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354680_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354680_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.448, -0.536, 0.66]} rotation={[-0.866, -0.081, -1.665]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354719_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354719_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354719_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354719_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.208, -0.099, 0.759]} rotation={[-2.461, 0.087, 1.472]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354758_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354758_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354758_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354758_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.207, -0.098, 0.09]} rotation={[-1.567, -0.921, -3.14]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354797_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354797_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354797_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354797_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.75]} rotation={[-Math.PI / 2, 0.709, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354835_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354835_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354835_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354835_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.084]} rotation={[0.075, 0.617, -0.108]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354876_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354876_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354876_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354876_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.232, 0.18, 0.752]} rotation={[3.045, 0.614, -3.039]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354914_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354914_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354914_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354914_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.232, 0.18, 0.752]} rotation={[3.058, 0.616, 0.106]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354952_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354952_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354952_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354952_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.207, -0.098, 0.09]} rotation={[0.862, -0.116, -1.348]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354992_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354992_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354992_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621354992_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.076, 0.66]} rotation={[2.249, -0.121, 1.323]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621355030_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621355030_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621355030_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621355030_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.258, 0.492, 0.371]} rotation={[0, 0.554, -2.571]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426114_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426114_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426114_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426114_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.076, 0.66]} rotation={[3.025, 0.616, 2.575]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426153_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426153_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426153_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426153_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.076, 0.18]} rotation={[-Math.PI / 2, -0.02, Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426191_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426191_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426191_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426191_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.076, 0.66]} rotation={[0, -0.02, Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426229_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426229_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426229_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426229_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.536, 0.18]} rotation={[Math.PI, -0.02, Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426272_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426272_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426272_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426272_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.076, 0.18]} rotation={[2.957, 0.419, 0.789]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426310_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426310_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426310_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426310_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.171, -0.517, 0.768]} rotation={[0.218, 0.469, -0.83]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426348_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426348_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426348_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426348_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.18]} rotation={[-3.121, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426386_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426386_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426386_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426386_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.536, 0.66]} rotation={[-0.002, -0.018, 1.571]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426424_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426424_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426424_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426424_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.19]} rotation={[0, -0.522, -Math.PI / 2]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426461_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426461_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426461_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426461_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.536, 0.42]} rotation={[-Math.PI, -0.527, Math.PI / 2]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426503_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426503_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426503_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426503_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.75]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426542_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426542_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426542_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426542_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.168, -0.536, 0.084]} rotation={[-2.371, -0.001, -1.57]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426579_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426579_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426579_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426579_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.248, -0.536, -0.249]} rotation={[-1.572, 0.8, -3.14]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426618_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426618_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426618_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426618_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.536, 1.088]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426655_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426655_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426655_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426655_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.536, -0.249]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426693_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426693_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426693_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426693_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.436, -0.249]} rotation={[0, 0, -0.029]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426732_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426732_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426732_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621426732_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.248, -0.436, -0.249]} rotation={[0, 0.001, Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477307_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477307_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477307_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477307_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.248, -0.536, 1.088]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477348_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477348_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477348_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477348_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.248, -0.436, 1.088]} rotation={[0, 0, -Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477398_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477398_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477398_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477398_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.248, -0.436, 1.088]} rotation={[0.087, 0, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477440_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477440_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477440_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477440_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.536, 1.088]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477481_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477481_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477481_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477481_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.668, -0.536, 0.988]} rotation={[0.955, 0.524, 0.955]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477522_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477522_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477522_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477522_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.668, -0.536, -0.149]} rotation={[Math.PI / 2, 0.785, 0]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477562_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477562_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477562_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477562_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.568, -0.536, -0.249]} rotation={[2.186, 0.524, -0.955]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477600_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477600_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477600_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477600_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.668, -0.436, -0.149]} rotation={[0.285, -0.055, -0.032]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477641_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477641_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477641_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477641_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.668, -0.436, -0.149]} rotation={[0, -0.05, Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477683_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477683_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477683_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477683_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.665, -0.295, 0.752]} rotation={[Math.PI / 2, -0.043, Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477722_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477722_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477722_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477722_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.665, -0.295, 0.752]} rotation={[1.353, -0.043, -0.004]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477761_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477761_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477761_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477761_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[1.668, -0.536, 0.988]} rotation={[-Math.PI, -0.06, -Math.PI]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477800_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477800_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477800_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477800_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.449, -0.116, 0.179]} rotation={[0.643, -0.004, -0.005]}>
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477837_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477837_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477837_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.ANSI_1_x_0179_1714621477837_4.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.463, -0.536, 0.661]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524620_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524620_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524620_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524620_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524620_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524620_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.813, -0.536, 0.705]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524694_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524694_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524694_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524694_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524694_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524694_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.813, -0.536, 0.741]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524766_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524766_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524766_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524766_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524766_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524766_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.813, -0.536, 0.941]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524841_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524841_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524841_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524841_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524841_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524841_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.463, -0.536, 0.941]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524912_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524912_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524912_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524912_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524912_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524912_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.463, -0.536, 0.741]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524987_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524987_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524987_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524987_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524987_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621524987_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.813, -0.536, 0.134]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525057_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525057_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525057_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525057_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525057_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525057_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.813, -0.536, 0.098]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525127_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525127_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525127_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525127_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525127_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525127_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.813, -0.536, -0.102]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525198_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525198_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525198_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525198_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525198_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525198_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.463, -0.536, 0.098]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525270_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525270_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525270_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525270_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525270_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525270_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.463, -0.536, -0.102]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525345_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525345_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525345_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525345_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525345_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525345_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.813, -0.536, -0.102]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525416_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525416_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525416_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525416_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525416_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.AISC_1_4x3_8_1714621525416_6.geometry} material={materials.mat_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')
